# Generated by Django 5.0.3 on 2024-03-17 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAtribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ключ')),
                ('value', models.CharField(max_length=150, verbose_name='значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribute', to='core.product')),
            ],
            options={
                'verbose_name': 'атрибут',
                'verbose_name_plural': 'атрибуты',
            },
        ),
    ]
